commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from . import views,util

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>",views.display,name="display_entry"),
    path("search/",views.search,name="search"),
    path("create/",views.create,name="create"),
    path("edit/",views.edit,name="edit"),
    path("random/",views.rand,name="random")
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import re
from sys import hash_info
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms
import random


from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


# This function is my arch nemesis, I correct one thing and it ruins another.
# I did it? I did it!!!
def convert(content):

    # Standardizing line endings, got this idea when I looked at the source code of markdown2's convert function.
    # One of the few things that didn't go over my head.
    content = content.replace("\r\n", "\n")
    content = content.replace("\r", "\n")
    content = content + "\n\n"

    # Adding heading tags to all headings depending on number of hash symbols
    heading_pattern = re.compile(r"(?<!\\)(\n|^)(#{1,6})(\s+.*?)(?=\n)")
    headings = re.finditer(heading_pattern, content)
    for heading in headings:
        hx = len(heading.groups()[1])
        content = re.sub(
            heading.group(),
            "\n<h" + str(hx) + ">" + heading.groups()[2] + "</h" + str(hx) + ">\n",
            content,
            count=1,
        )

    # Detecting unordered list
    ul_pattern = re.compile(r"(?ms)\n\n(?<!\\)\*\s(.+?)\n\n")
    u_lists = re.finditer(ul_pattern, content)
    ul_spans = []
    for ul in u_lists:
        ul_spans.append(ul.start())
        ul_spans.append((ul.end() + 11))
        content = re.sub(
            re.escape(ul.group()), "<ul>" + ul.group() + r"</ul>\n\n", content,count=1
        )
        

    # Adding list items to list
    li_pattern = re.compile(r"(?m)(?<!\\)(^\*)(?=\s+)(.+?)(?=\n)")
    list_items = re.finditer(li_pattern, content)
    for item in list_items:
        for i in range(0,len(ul_spans),2):
            if  ul_spans[i] < item.start() < ul_spans[i+1]:
                content = re.sub(
                    re.escape(item.group()), "<li>" + item.groups()[1] + "</li>", content,count=1
                )

    # Detecting and substituting links
    link_pattern = re.compile(r"(?<!\\)\[(.+?)(?<!\\)\]((?<!\\)\(.+?(?<!\\)\))")
    links = re.finditer(link_pattern, content)
    for link in links:
        content = re.sub(
            re.escape(link.group()),
            "<a href=" + link.groups()[1] + ">" + link.groups()[0] + "</a>",
            content,
            count=1,
        )

    # Adding <b> tag to bold text
    bold_pattern = re.compile(r"(?<!\\)(\*|_){2}(?!\s)(.+?)(?<!\\)(\*|_){2}")
    bold_texts = re.finditer(bold_pattern, content)
    for bold_text in bold_texts:
        content = re.sub(
            re.escape(bold_text.group()),
            "<b>" + bold_text.groups()[1] + "</b>",
            content,
            count=1,
        )

    # Adding <i> tag to italic text
    italic_pattern = re.compile(
        r"(?<!\<br\>)(?<!\\)(\*|_){1}(?!\s)(.+?)(?<!\\)(\*|_){1}"
    )
    italic_texts = re.finditer(italic_pattern, content)
    for italic_text in italic_texts:
        content = re.sub(
            re.escape(italic_text.group()),
            "<i>" + italic_text.groups()[1] + "</i>",
            content,
            count=1,
        )
    
    # Paragraph detection... This was hell.
    para_pattern = re.compile(r"(\n\s*\n|^)((?!\n*\</?h|\n*\</?ul|\n*\</?li).+?)(?=\n\s*\n|\n*\<h|\n*\<ul|\n*\<li|$)",re.DOTALL)
    paras = re.finditer(para_pattern, content)
    for para in paras:
        content = re.sub(
            re.escape(para.group()), "<p>" + para.groups()[1] + "</p>", content, count=1
        )

    # Adding line breaks when detecting markdown linebreak (double space or back slash)
    newline_pattern = re.compile(r"(?<!\n)[\s]*(  |\\)\n[\s]*(?!\n)")
    content = re.sub(newline_pattern,"<br>",content)

    # Removing excess newlines (just to clean things up)
    content = content.replace("\n","")

    # Removing \ when before special characters
    content = content.replace("\*","*")
    content = content.replace("\#","#")
    content = content.replace("\_","_")
    return content


def display(request, entry):
    content = util.get_entry(entry)

    if not content:
        return render(request, "encyclopedia/not_found.html")

    content = convert(content)

    return render(
        request, "encyclopedia/display.html", {"content": content, "entry": entry}
    )


def search(request):
    query = request.GET["q"]
    query = str(query)
    entries = util.list_entries()
    sub_of = []
    for entry in entries:
        if entry.lower() == query.lower():
            return HttpResponseRedirect("/" + query)
        if query.lower() in entry.lower():
            sub_of.append(entry)

    return render(request, "encyclopedia/search.html", {"entries": sub_of})


class CreateForm(forms.Form):
    title = forms.CharField(label="Page Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": 25, "cols": 25}))


def create(request):

    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            entries = util.list_entries()
            for entry in entries:
                if title.lower() == entry.lower():
                    return HttpResponse("<h1>Error: Title already in use</h1>")

            try:
                util.save_entry(title, content)
                return HttpResponseRedirect("/" + title)
            except:
                return HttpResponse("Something went wrong")

        return HttpResponseRedirect("")
    else:
        return render(request, "encyclopedia/create.html")


class EditForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": 25, "cols": 25}))
    entry = forms.CharField()


def edit(request):

    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            new_content = form.cleaned_data["content"]
            current_entry = form.cleaned_data["entry"]
            try:
                new_content = new_content.replace("\r","")
                util.save_entry(current_entry, new_content)
            except:
                return HttpResponse("<h1>Something's wrong!</h1>")
        return HttpResponseRedirect("/" + current_entry)
    else:
        entry = request.GET["entry"]
        content = util.get_entry(entry)
        content = content.replace("\r\r","")
        return render(
            request, "encyclopedia/edit.html", {"entry": entry, "content": content}
        )


def rand(request):
    R = random.choice(util.list_entries())
    return HttpResponseRedirect("/" + R)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

<h1>Create new page</h1>
<div class="container-fluid col-lg-8 col-md-8">
<form action="{% url 'encyclopedia:create' %}" method="post">
    {% csrf_token %}
    <label for="title">Title</label>
    <input class="form-control" type="text" name = "title">
    <br>
    <br>
    <p>Content</p>
    <textarea class="form-control" name="content" cols="25" rows="25" placeholder="Content"></textarea>
    <br>
    <input type="submit" value="Save Page" class="btn btn-success">
</form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/display.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{entry}}
{% endblock %}

{% block body %}
    
        {{ content | safe}}
        <hr style="border: 1px solid black;">
        <form action="{% url 'encyclopedia:edit' %}">
            <input type="hidden" value="{{entry}}" name="entry">
            <button class="btn btn-warning" type="submit">Edit page</button>
        </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

<h1>Edit "{{entry}}" page</h1>
<div class="container-fluid col-lg-8 col-md-8">
<form action="{% url 'encyclopedia:edit' %}" method="post">
    {% csrf_token %}
    <br>
    <p>Content</p>
    <input type="hidden" name="entry" value="{{entry}}">
    <textarea class="form-control" name="content" cols="25" rows="25">{{content}}</textarea>
    <br>
    <input type="submit" value="Save Page" class="btn btn-success">
</form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{entry}}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}">
                <input autocomplete="off" class="search" type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>The page you requested was not found</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

<h1>Results</h1>

<ul>
    {% for entry in entries %}
    <li><a href="/{{entry}}">{{ entry }}</a></li>
    {% empty %}
    <h3 style="color: red;">No Entries Found</h3>
    {% endfor %}
</ul>

{% endblock %}